/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Control.ChessController;
import Exceptions.PieceNotFoundException;
import itcr.Logic.ChessColor;
import itcr.Logic.Piece;
import itcr.Logic.PieceTypes;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import static java.lang.Math.abs;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author lito
 */
public class BoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form BoardPanel
     */
    ChessController control = ChessController.getInstance();
    GameWindow gameWindow;
    Point boardPos;
    List<ChessController.GraphicPiece> pieces;
    BufferedImage image;
    Image sprite;
    Image selectionSprite;
    Image squareIndicatorSprite;
    boolean pieceSelected = false;
    private int selectedPieceX = -1;
    private int selectedPieceY = -1;
    private int targetX = -1;
    private int targetY = -1;
    
    private void paintValidSquares(Graphics2D g) {
        try {
            List<List> validMoves = control.getValidMoves(selectedPieceX, selectedPieceY);
            for (List pos : validMoves) {
                int x = (int) pos.get(0);
                int y = (int) pos.get(1);
                g.drawImage(squareIndicatorSprite,
                        x * ChessController.TILE_SIZE + 3,
                        y * ChessController.TILE_SIZE + 3,
                        null);
            }
        } catch (Exception ex) {
            Logger.getLogger(BoardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public BoardPanel(GameWindow gameWindow) {
        try {
            initComponents();
            setBounds(0, 0, ChessController.TILE_SIZE * control.getBoardRanks() + 6, ChessController.TILE_SIZE * control.getBoardFiles() + 6);
            pieces = control.getPiecesList();
            this.gameWindow = gameWindow;
            String path = "src/main/resources/graphics/";
            image = ImageIO.read(new FileInputStream(path + "chessboard.png"));
            sprite = image.getScaledInstance(
                    ChessController.TILE_SIZE * control.getBoardRanks() + 6,
                    ChessController.TILE_SIZE * control.getBoardFiles() + 6,
                BufferedImage.SCALE_SMOOTH
            );
            
            image = ImageIO.read(new FileInputStream(path + "boardselection.png"));
            selectionSprite = image.getScaledInstance(ChessController.TILE_SIZE, ChessController.TILE_SIZE, BufferedImage.SCALE_SMOOTH);
            
            image = ImageIO.read(new FileInputStream(path + "validsquareindicator.png"));
            squareIndicatorSprite = image.getScaledInstance(ChessController.TILE_SIZE, ChessController.TILE_SIZE, BufferedImage.SCALE_SMOOTH);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BoardPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BoardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void refresh() {
        control = ChessController.getInstance();
        pieces = control.getPiecesList();
        repaint();
    }
    
    public void deselect() {
        pieceSelected = false;
        repaint();
    }
    
    public void performPromotion(PieceTypes type) {
        control.promotePawn(targetX, targetY, type);
        pieces = control.getPiecesList();
        repaint();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2D = (Graphics2D) g;
        g2D.drawImage(sprite, 0, 0, null);
        for (ChessController.GraphicPiece p : pieces) {
            p.paint(g2D);
        }
        if (pieceSelected) {
            g2D.drawImage(selectionSprite,
                    selectedPieceX * ChessController.TILE_SIZE + 3,
                    selectedPieceY * ChessController.TILE_SIZE + 3,
            null);
            paintValidSquares(g2D);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (!isFocusable()) {
            return;
        }
        Point mousePos = MouseInfo.getPointerInfo().getLocation();
        boardPos = getLocationOnScreen();
        if (!pieceSelected) {
            try {
                selectedPieceX = abs(boardPos.x + 3 - mousePos.x) / ChessController.TILE_SIZE;
                selectedPieceY = abs(boardPos.y + 3 - mousePos.y) / ChessController.TILE_SIZE;
                if (control.doesPieceInSquareBelongToPlayer(selectedPieceX, selectedPieceY)) {
                    //Piece p = control.DEBUG_getPieceInSquare(selectedPieceX, selectedPieceY);
                    //JOptionPane.showMessageDialog(this, String.format(
                    //    "sPieceX: %s, sPieceY: %s\nPiece X: %s, Piece Y: %s",
                    //        selectedPieceX, selectedPieceY, p.getX(), p.getY()
                    //));
                    pieceSelected = true;
                    repaint();
                } else {
                    String n = control.getCurrentPlayerName();
                    JOptionPane.showMessageDialog(this, "It's " + n + "'s turn.");
                }
            } catch (PieceNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                pieceSelected = false;
            }
        } else {
            //int targetX, targetY;
            targetX = abs(boardPos.x + 3 - mousePos.x) / ChessController.TILE_SIZE;
            targetY = abs(boardPos.y + 3 - mousePos.y) / ChessController.TILE_SIZE;
            try {
                control.movePiece(selectedPieceX, selectedPieceY, targetX, targetY);
                pieces = control.getPiecesList();
                pieceSelected = false;
                repaint();
                if (control.isAwaitingPromotion()) {
                    new PromotionWindow(gameWindow).setVisible(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                pieceSelected = false;
            }
        }
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
